name: Flutter Release
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D @semantic-release/exec git status cat pubspec.yaml
      - name: release
        run: npx semantic-release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
