name: Flutter Release
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          node-version: '15.x'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Run a multi-line script
        run: flutter test

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      -  run: npm ci
      -  run: npm run semantic-release
