name: Update Version
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  create_tag_and_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup semantic-release
      - run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D @semantic-release/exec
      - name: release
      - run: npx semantic-release



