name: Update Version
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  create_tag_and_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - id: setup_semantic_release
        run: npm install -g @semantic-release/git @semantic-release/changelog -D @semantic-release/exec
      - id: release
        run: npx semantic-release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

