name: Update Version
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  create_tag_and_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D @semantic-release/exec
      - name: release
      - run: npx semantic-release
  list_variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: env

  update_pubspec:
    name: Updating the code version and commiting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Mandatory to use the extract version from tag action
          fetch-depth: 0
      - name: Extract version from tag
        # With this, we can extract the version of the new tag
        #  and use it with Cider
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}

      # Get dependencies and generating appbundle
      # Here I'm using appbundle, feel free to change it to APK
      - run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          pub global activate cider
          cider version ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}+${{ env.NUMBER_OF_COMMITS }}
          flutter pub get
      # Here we have already updated the version on pubspec.yaml
      # But, tha changes are not commited to version control
      # Now, let's do it!
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          # Change it to your own branch
          branch: master
          message: "Update version on pubspec.yaml & update change log"
          # Change it to your own branch
          push: origin master --force
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  JAVA_VERSION: "12.x"
  #change it to your project version
  FLUTTER_VERSION: "3.x"
  #change it to your project channel
  FLUTTER_CHANNEL: "stable"
