name: Update Version
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  create_tag_and_changelog:
    runs-on: ubuntu-latest
    steps:
      - id: step1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D @semantic-release/exec
      - name: release
        run: npx semantic-release
    outputs:
      output1: ${{steps.step2.outputs}}

  update_pubspec:
    runs-on: ubuntu-latest
    needs: create_tag_and_changelog
    steps:
      - run: echo ${{needs.create_tag_and_changelog.outputs.output1}}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  JAVA_VERSION: "12.x"
  #change it to your project version
  FLUTTER_VERSION: "3.x"
  #change it to your project channel
  FLUTTER_CHANNEL: "stable"
